using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._PS.Interactions;
using Content.Shared._PS.Organs;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._PS.Interactions;

/// <summary>
/// Client window for the interaction panel. Adapted from Sandstorm's TGUI MobInteraction
/// interface to the SS14 XAML controls; layout differs, functionality (search, favorites,
/// auto-repeat, genital visibility, preferences) is preserved.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class InteractionWindow : FancyWindow
{
    public event Action<string>? OnInteractionSelected;
    public event Action<string>? OnAutoToggled;
    public event Action<string>? OnFavoriteToggled;
    public event Action<float>? OnPaceChanged;
    public event Action<bool>? OnConsentChanged;
    public event Action<bool>? OnSoundsChanged;
    public event Action<bool, double>? OnArousalMultiplierChanged;
    public event Action<bool, double>? OnMoaningMultiplierChanged;
    public event Action<GenitalType, bool>? OnGenitalAroused;
    public event Action<GenitalType, GenitalVisibility>? OnGenitalVisibilityChanged;

    private const string PlayIcon = "/Textures/Interface/AdminActions/play.png";
    private const string PauseIcon = "/Textures/Interface/AdminActions/pause.png";
    private const string StarIcon = "/Textures/Interface/examine-star.png";

    /// <summary>
    /// Compact button style for the interaction list. The theme's texture style box has a 24px
    /// 9-slice patch that makes each row huge; this keeps the theme's per-state modulate but
    /// shrinks the minimum height to a single text line.
    /// </summary>
    private static readonly StyleBoxFlat CompactButtonStyle = new()
    {
        BackgroundColor = Color.White,
        BorderThickness = new Thickness(1),
        BorderColor = Color.FromHex("#8a8a8a"),
        ContentMarginTopOverride = 0,
        ContentMarginBottomOverride = 0,
        ContentMarginLeftOverride = 4,
        ContentMarginRightOverride = 4,
    };

    private const int RowHeight = 18;

    /// <summary>play.png/pause.png are 32x32; the star is 64x64. Both are scaled to 16px so the
    /// texture buttons do not inflate the interaction rows (TextureButton measures its texture).</summary>
    private static readonly Vector2 PlayIconScale = new(0.5f, 0.5f);
    private static readonly Vector2 StarIconScale = new(0.25f, 0.25f);
    private const int IconSize = 16;

    private InteractionBoundUserInterfaceState? _state;
    private bool _updating;
    private string _search = string.Empty;
    private bool _favoritesOnly;

    public InteractionWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, Loc.GetString("interaction-tab-interactions"));
        Tabs.SetTabTitle(1, Loc.GetString("interaction-tab-genitals"));
        Tabs.SetTabTitle(2, Loc.GetString("interaction-tab-preferences"));
        Tabs.OnTabChanged += _ => UpdateAutoBarVisibility();

        SearchBar.OnTextChanged += args =>
        {
            _search = args.Text;
            RebuildInteractions();
        };

        FavoritesFilterButton.OnToggled += args =>
        {
            _favoritesOnly = args.Pressed;
            RebuildInteractions();
        };

        StopAutoButton.OnPressed += _ =>
        {
            if (_state?.ActiveAutoInteraction is { } id)
                OnAutoToggled?.Invoke(id);
        };

        PaceSlider.OnValueChanged += _ =>
        {
            if (_updating || _state == null || _state.Speeds.Count == 0)
                return;

            var index = Math.Clamp((int) MathF.Round(PaceSlider.Value) - 1, 0, _state.Speeds.Count - 1);
            OnPaceChanged?.Invoke(_state.Speeds[index]);
        };

        ConsentCheck.OnToggled += args =>
        {
            if (!_updating)
                OnConsentChanged?.Invoke(args.Pressed);
        };

        SoundsCheck.OnToggled += args =>
        {
            if (!_updating)
                OnSoundsChanged?.Invoke(args.Pressed);
        };

        ArousalMultiplierCheck.OnToggled += args =>
        {
            if (!_updating)
                OnArousalMultiplierChanged?.Invoke(args.Pressed, ArousalMultiplierSlider.Value);
        };

        ArousalMultiplierSlider.OnValueChanged += _ =>
        {
            if (!_updating)
                OnArousalMultiplierChanged?.Invoke(ArousalMultiplierCheck.Pressed, ArousalMultiplierSlider.Value);
        };

        MoaningMultiplierCheck.OnToggled += args =>
        {
            if (!_updating)
                OnMoaningMultiplierChanged?.Invoke(args.Pressed, MoaningMultiplierSlider.Value);
        };

        MoaningMultiplierSlider.OnValueChanged += _ =>
        {
            if (!_updating)
                OnMoaningMultiplierChanged?.Invoke(MoaningMultiplierCheck.Pressed, MoaningMultiplierSlider.Value);
        };
    }

    public void UpdateState(InteractionBoundUserInterfaceState state)
    {
        _state = state;

        _updating = true;
        try
        {
            TargetLabel.Text = Loc.GetString(
                state.TargetIsSelf ? "interaction-interacting-with-self" : "interaction-interacting-with",
                ("target", state.TargetName));
            SelfAttributes.Text = string.Join("\n", state.SelfAttributes);
            TargetAttributes.Text = string.Join("\n", state.TargetAttributes);
            TargetAttributes.Visible = !state.TargetIsSelf;

            LustBar.MaxValue = (float) Math.Max(state.MaxLust, 1);
            LustBar.Value = (float) state.Lust;
            TargetLustBar.Visible = !state.TargetIsSelf;
            TargetLustBar.MaxValue = (float) Math.Max(state.TargetMaxLust, 1);
            TargetLustBar.Value = (float) state.TargetLust;

            ConsentCheck.Text = Loc.GetString("interaction-consent");
            ConsentCheck.Pressed = state.Consent;
            SoundsCheck.Text = Loc.GetString("interaction-lewd-sounds");
            SoundsCheck.Pressed = state.LewdSounds;

            ArousalMultiplierCheck.Text = Loc.GetString("interaction-lust-gain");
            ArousalMultiplierCheck.Pressed = state.UseArousalMultiplier;
            ArousalMultiplierSlider.Value = (float) state.ArousalMultiplier;
            ArousalMultiplierSlider.Disabled = !state.UseArousalMultiplier;

            MoaningMultiplierCheck.Text = Loc.GetString("interaction-moaning");
            MoaningMultiplierCheck.Pressed = state.UseMoaningMultiplier;
            MoaningMultiplierSlider.Value = (float) state.MoaningMultiplier;
            MoaningMultiplierSlider.Disabled = !state.UseMoaningMultiplier;

            if (state.Speeds.Count > 0)
            {
                var index = state.Speeds.FindIndex(s => Math.Abs(s - state.AutoPace) < 0.001f);
                PaceSlider.Value = (index >= 0 ? index : 2) + 1;
            }
        }
        finally
        {
            _updating = false;
        }

        RebuildInteractions();
        RebuildGenitals();
        UpdateAutoBarVisibility();
    }

    private void UpdateAutoBarVisibility()
    {
        AutoBar.Visible = Tabs.CurrentTab == 0;
        StopAutoButton.Disabled = _state?.ActiveAutoInteraction == null;
    }

    private void RebuildInteractions()
    {
        InteractionsList.RemoveAllChildren();

        if (_state == null)
            return;

        var search = _search.Trim();
        var count = 0;

        foreach (var entry in _state.Interactions)
        {
            if (!entry.Available)
                continue;

            if (_favoritesOnly && !entry.Favorite)
                continue;

            if (search.Length > 0 &&
                !entry.Name.Contains(search, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            InteractionsList.AddChild(BuildInteractionRow(entry));
            count++;
        }

        if (count == 0)
        {
            var key = search.Length > 0
                ? "interaction-no-matching"
                : _favoritesOnly
                    ? "interaction-favorites-empty"
                    : "interaction-no-interactions";

            InteractionsList.AddChild(new Label
            {
                Text = Loc.GetString(key),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 8),
            });
        }
    }

    private Control BuildInteractionRow(InteractionUiEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
            MinHeight = RowHeight,
        };

        if (entry.Type != InteractionType.Normal)
        {
            var active = _state?.ActiveAutoInteraction == entry.Id;

            var auto = new TextureButton
            {
                TexturePath = active ? PauseIcon : PlayIcon,
                MinSize = new Vector2(IconSize, IconSize),
                Scale = PlayIconScale,
                ToolTip = Loc.GetString(active ? "interaction-auto-stop" : "interaction-auto-start"),
            };
            auto.OnPressed += _ => OnAutoToggled?.Invoke(entry.Id);
            row.AddChild(auto);
        }

        var main = new Button
        {
            Text = entry.Name,
            HorizontalExpand = true,
            MinHeight = RowHeight,
            ClipText = true,
            StyleBoxOverride = CompactButtonStyle,
        };
        main.OnPressed += _ => OnInteractionSelected?.Invoke(entry.Id);
        row.AddChild(main);

        var favorite = new TextureButton
        {
            TexturePath = StarIcon,
            MinSize = new Vector2(IconSize, IconSize),
            Scale = StarIconScale,
            Modulate = entry.Favorite ? Color.Gold : Color.Gray,
            ToolTip = Loc.GetString("interaction-favorite-toggle"),
        };
        favorite.OnPressed += _ => OnFavoriteToggled?.Invoke(entry.Id);
        row.AddChild(favorite);

        return row;
    }

    private void RebuildGenitals()
    {
        GenitalsList.RemoveAllChildren();

        if (_state == null)
            return;

        if (_state.Genitals.Count == 0)
        {
            GenitalsList.AddChild(new Label
            {
                Text = Loc.GetString("interaction-no-genitals"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 8),
            });
            return;
        }

        foreach (var genital in _state.Genitals)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                MinHeight = 22,
            };

            var label = string.IsNullOrEmpty(genital.SizeName)
                ? genital.Name
                : $"{genital.Name} ({genital.SizeName})";

            row.AddChild(new Label
            {
                Text = label,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            });

            var visibility = new OptionButton
            {
                MinWidth = 140,
                MinHeight = 22,
                ToolTip = Loc.GetString("interaction-genital-visibility"),
            };
            visibility.AddItem(Loc.GetString("genital-visibility-always-hidden"), (int) GenitalVisibility.AlwaysHidden);
            visibility.AddItem(Loc.GetString("genital-visibility-hidden-by-underwear"), (int) GenitalVisibility.HiddenByUnderwear);
            visibility.AddItem(Loc.GetString("genital-visibility-hidden-by-jumpsuit"), (int) GenitalVisibility.HiddenByJumpsuit);
            visibility.AddItem(Loc.GetString("genital-visibility-never-hidden"), (int) GenitalVisibility.NeverHidden);
            visibility.SelectId((int) genital.Visibility);
            visibility.Disabled = !genital.CanToggleArousal;
            visibility.OnItemSelected += args =>
            {
                visibility.SelectId(args.Id);
                OnGenitalVisibilityChanged?.Invoke(genital.Type, (GenitalVisibility) args.Id);
            };
            row.AddChild(visibility);

            var toggle = new Button
            {
                Text = Loc.GetString(genital.Aroused ? "interaction-genital-unarouse" : "interaction-genital-arouse"),
                Disabled = !genital.CanToggleArousal,
                MinWidth = 80,
                MinHeight = 22,
            };
            toggle.OnPressed += _ => OnGenitalAroused?.Invoke(genital.Type, !genital.Aroused);
            row.AddChild(toggle);

            GenitalsList.AddChild(row);
        }
    }
}
