using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._PS.HilbertHotel;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Random;

namespace Content.Client._PS.HilbertHotel;

[GenerateTypedNameReferences]
public sealed partial class HilbertHotelTeleporterWindow : DefaultWindow
{
    public event Action<int, string?>? CheckInPressed;
    public event Action<int>? DeletePressed;
    public event Action? RefreshPressed;

    private readonly Dictionary<string, (Button Button, string Name)> _templateButtons = new();
    private string? _selectedTemplate;

    public HilbertHotelTeleporterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CheckInButton.OnPressed += _ => TryCheckIn();
        RandomButton.OnPressed += _ => CodeEdit.Text = IoCManager.Resolve<IRobustRandom>()
            .Next(HilbertHotelConstants.MinRoomCode, HilbertHotelConstants.MaxRoomCode + 1)
            .ToString();
        RefreshButton.OnPressed += _ => RefreshPressed?.Invoke();
    }

    public void UpdateState(HilbertHotelTeleporterStateMessage state)
    {
        BuildTemplates(state);
        BuildRooms(state);

        RoomCountLabel.Text = Loc.GetString(
            "hilbert-hotel-teleporter-room-count",
            ("count", state.RoomCount),
            ("max", state.MaxRooms));
    }

    private void TryCheckIn()
    {
        if (!int.TryParse(CodeEdit.Text, out var code))
        {
            CodeEdit.Text = string.Empty;
            return;
        }

        CheckInPressed?.Invoke(code, _selectedTemplate);
    }

    private void BuildTemplates(HilbertHotelTeleporterStateMessage state)
    {
        var selectedStillExists = false;
        foreach (var template in state.Templates)
        {
            if (template.Id == _selectedTemplate)
                selectedStillExists = true;
        }

        if (!selectedStillExists)
            _selectedTemplate = state.Templates.Count > 0 ? state.Templates[0].Id : null;

        TemplateContainer.DisposeAllChildren();
        _templateButtons.Clear();

        foreach (var template in state.Templates)
        {
            var button = new Button
            {
                HorizontalExpand = true,
                ClipText = true,
            };

            var id = template.Id;
            button.OnPressed += _ =>
            {
                _selectedTemplate = id;
                UpdateTemplateSelectionVisuals();
            };

            TemplateContainer.AddChild(button);
            _templateButtons[id] = (button, template.Name);
        }

        UpdateTemplateSelectionVisuals();
    }

    private void UpdateTemplateSelectionVisuals()
    {
        foreach (var (id, entry) in _templateButtons)
        {
            var selected = id == _selectedTemplate;
            entry.Button.Text = selected
                ? Loc.GetString("hilbert-hotel-teleporter-template-selected", ("name", entry.Name))
                : entry.Name;
            entry.Button.ModulateSelfOverride = selected ? Color.LimeGreen : null;
        }
    }

    private void BuildRooms(HilbertHotelTeleporterStateMessage state)
    {
        RoomContainer.DisposeAllChildren();

        if (state.Rooms.Count == 0)
        {
            RoomContainer.AddChild(new Label
            {
                Text = Loc.GetString("hilbert-hotel-teleporter-no-rooms"),
            });
            return;
        }

        foreach (var room in state.Rooms)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            row.AddChild(new Label
            {
                Text = FormatRoom(room),
                HorizontalExpand = true,
                ClipText = true,
                VerticalAlignment = VAlignment.Center,
            });

            if (room.CanJoin)
            {
                var join = new Button
                {
                    Text = Loc.GetString("hilbert-hotel-teleporter-join"),
                    MinSize = new Vector2(70, 0),
                };
                var code = room.Code;
                join.OnPressed += _ => CheckInPressed?.Invoke(code, _selectedTemplate);
                row.AddChild(join);
            }

            if (room.IsOwner)
            {
                var delete = new ConfirmButton
                {
                    Text = Loc.GetString("hilbert-hotel-teleporter-delete"),
                    ConfirmationText = Loc.GetString("hilbert-hotel-teleporter-delete-confirm"),
                    MinSize = new Vector2(70, 0),
                };
                var code = room.Code;
                delete.OnPressed += _ => DeletePressed?.Invoke(code);
                row.AddChild(delete);
            }

            RoomContainer.AddChild(row);
        }
    }

    private string FormatRoom(HilbertHotelRoomEntry room)
    {
        var status = Loc.GetString(room.Status switch
        {
            HilbertHotelRoomStatus.Open => "hilbert-hotel-status-open",
            HilbertHotelRoomStatus.GuestsOnly => "hilbert-hotel-status-guests",
            _ => "hilbert-hotel-status-locked",
        });

        return Loc.GetString(
            "hilbert-hotel-teleporter-room-entry",
            ("code", room.Code),
            ("name", room.Name),
            ("owner", room.OwnerName),
            ("status", status),
            ("count", room.Occupants));
    }
}
