using System.Numerics;
using Content.Shared._PS.HilbertHotel;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client._PS.HilbertHotel;

[GenerateTypedNameReferences]
public sealed partial class HilbertHotelRoomControllerWindow : DefaultWindow
{
    public event Action<HilbertHotelRoomAction, NetUserId>? ActionPressed;

    private bool _updating;

    public HilbertHotelRoomControllerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StatusButton.OnPressed += _ => Send(HilbertHotelRoomAction.CycleStatus);
        VisibilityCheckBox.OnToggled += _ =>
        {
            if (!_updating)
                Send(HilbertHotelRoomAction.ToggleVisibility);
        };
        ClearGuestsButton.OnPressed += _ => Send(HilbertHotelRoomAction.ClearGuests);
        DeleteButton.OnPressed += _ => Send(HilbertHotelRoomAction.DeleteRoom);
    }

    public void UpdateState(HilbertHotelRoomControllerStateMessage state)
    {
        _updating = true;

        CodeLabel.Text = Loc.GetString("hilbert-hotel-controller-code", ("code", state.Code));
        OwnerLabel.Text = Loc.GetString("hilbert-hotel-controller-owner", ("name", state.OwnerName));
        NotOwnerLabel.Visible = !state.IsOwner;

        StatusButton.Text = Loc.GetString(
            "hilbert-hotel-controller-status-button",
            ("status", StatusName(state.Status)));
        StatusButton.Disabled = !state.IsOwner;

        VisibilityCheckBox.Pressed = state.Visible;
        VisibilityCheckBox.Disabled = !state.IsOwner;

        GuestContainer.DisposeAllChildren();
        if (state.Guests.Count == 0)
        {
            GuestContainer.AddChild(new Label
            {
                Text = Loc.GetString("hilbert-hotel-controller-no-guests"),
            });
        }

        foreach (var guest in state.Guests)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            row.AddChild(new Label
            {
                Text = guest.Name,
                HorizontalExpand = true,
                ClipText = true,
                VerticalAlignment = VAlignment.Center,
            });

            if (state.IsOwner)
            {
                var remove = new Button
                {
                    Text = Loc.GetString("hilbert-hotel-controller-remove"),
                    MinSize = new Vector2(80, 0),
                };
                var id = guest.UserId;
                remove.OnPressed += _ => Send(HilbertHotelRoomAction.RemoveGuest, id);
                row.AddChild(remove);
            }

            GuestContainer.AddChild(row);
        }

        ClearGuestsButton.Disabled = !state.IsOwner || state.Guests.Count == 0;
        DeleteButton.Disabled = !state.IsOwner;

        OccupantContainer.DisposeAllChildren();
        if (state.Occupants.Count == 0)
        {
            OccupantContainer.AddChild(new Label
            {
                Text = Loc.GetString("hilbert-hotel-controller-no-occupants"),
            });
        }

        foreach (var occupant in state.Occupants)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            var label = occupant.Name;
            if (occupant.IsOwner)
                label = Loc.GetString("hilbert-hotel-controller-occupant-owner", ("name", label));
            else if (occupant.Trusted)
                label = Loc.GetString("hilbert-hotel-controller-occupant-trusted", ("name", label));

            row.AddChild(new Label
            {
                Text = label,
                HorizontalExpand = true,
                ClipText = true,
                VerticalAlignment = VAlignment.Center,
            });

            if (state.IsOwner && !occupant.IsOwner)
            {
                if (!occupant.Trusted)
                {
                    var trust = new Button
                    {
                        Text = Loc.GetString("hilbert-hotel-controller-trust"),
                        MinSize = new Vector2(80, 0),
                    };
                    var id = occupant.UserId;
                    trust.OnPressed += _ => Send(HilbertHotelRoomAction.AddGuest, id);
                    row.AddChild(trust);
                }

                var transfer = new Button
                {
                    Text = Loc.GetString("hilbert-hotel-controller-transfer"),
                    MinSize = new Vector2(80, 0),
                };
                var target = occupant.UserId;
                transfer.OnPressed += _ => Send(HilbertHotelRoomAction.TransferOwnership, target);
                row.AddChild(transfer);
            }

            OccupantContainer.AddChild(row);
        }

        _updating = false;
    }

    private void Send(HilbertHotelRoomAction action, NetUserId target = default)
    {
        ActionPressed?.Invoke(action, target);
    }

    private string StatusName(HilbertHotelRoomStatus status)
    {
        return Loc.GetString(status switch
        {
            HilbertHotelRoomStatus.Open => "hilbert-hotel-status-open",
            HilbertHotelRoomStatus.GuestsOnly => "hilbert-hotel-status-guests",
            _ => "hilbert-hotel-status-locked",
        });
    }
}
