using Content.Shared.Chat.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Palmtree/Coyote: character editor window that lets a player pick which emote
/// categories appear in their radial emote wheel.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class EmoteCategoryWindow : DefaultWindow
{
    private static readonly Dictionary<EmoteCategory, string> CategoryTooltips = new()
    {
        [EmoteCategory.General] = "emote-menu-category-general",
        [EmoteCategory.Hands] = "emote-menu-category-hands",
        [EmoteCategory.Harpy] = "emote-menu-category-harpy",
        [EmoteCategory.Goblin] = "emote-menu-category-goblin",
        [EmoteCategory.Vulp] = "emote-menu-category-vulp",
        [EmoteCategory.Rodentia] = "emote-menu-category-rodentia",
        [EmoteCategory.Diona] = "emote-menu-category-diona",
        [EmoteCategory.Sheleg] = "emote-menu-category-sheleg",
        [EmoteCategory.Male] = "emote-menu-category-male",
        [EmoteCategory.Female] = "emote-menu-category-female",
        [EmoteCategory.Avali] = "emote-menu-category-avali",
        [EmoteCategory.Lizard] = "emote-menu-category-lizard",
        [EmoteCategory.Vox] = "emote-menu-category-vox",
        [EmoteCategory.Moth] = "emote-menu-category-moth",
        [EmoteCategory.Borg] = "emote-menu-category-borg",
        [EmoteCategory.Felinid] = "emote-menu-category-felinid",
    };

    private readonly Dictionary<EmoteCategory, CheckBox> _categoryCheckboxes = new();
    private readonly HumanoidCharacterProfile? _currentProfile;

    public static int ConfigurableCategoryCount => CategoryTooltips.Count;

    public event Action<HumanoidCharacterProfile?>? OnSave;

    public EmoteCategoryWindow(HumanoidCharacterProfile? currentProfile)
    {
        RobustXamlLoader.Load(this);

        _currentProfile = currentProfile;

        SaveButton.OnPressed += _ => SaveAndClose();
        CancelButton.OnPressed += _ => Close();

        PopulateCategories();
    }

    private void PopulateCategories()
    {
        CategoriesContainer.DisposeAllChildren();
        _categoryCheckboxes.Clear();

        var sorted = new List<KeyValuePair<EmoteCategory, string>>(CategoryTooltips);
        sorted.Sort((a, b) => string.Compare(Loc.GetString(a.Value), Loc.GetString(b.Value), StringComparison.Ordinal));

        foreach (var entry in sorted)
        {
            var category = entry.Key;
            var tooltip = entry.Value;

            var hidden = _currentProfile?.HiddenEmoteCategories.Contains(category) == true;
            var checkBox = new CheckBox
            {
                Text = Loc.GetString(tooltip),
                Pressed = !hidden,
                HorizontalExpand = true,
            };

            _categoryCheckboxes[category] = checkBox;
            CategoriesContainer.AddChild(checkBox);
        }

        CategoriesContainer.AddChild(new Label
        {
            Margin = new Thickness(0, 8, 0, 0),
            FontColorOverride = Color.Gray,
            Text = Loc.GetString("emote-window-always-enabled")
        });
    }

    private void SaveAndClose()
    {
        var updatedProfile = _currentProfile;

        foreach (var (category, checkBox) in _categoryCheckboxes)
        {
            var hidden = !checkBox.Pressed;
            updatedProfile = updatedProfile?.WithHiddenEmoteCategory(category, hidden);
        }

        OnSave?.Invoke(updatedProfile);
        Close();
    }
}
