// Commit-based changelog generator: appends entries for pushed commits that contain a
// ":cl:" block, for example:
//
//     Add a thing
//
//     :cl:
//     - add: Added a thing.
//     - fix: Fixed another thing.
//
// Commits generated by pull requests are skipped; those are handled by the pull
// request changelog workflow (changelog.yml).

// Dependencies
const fs = require("fs");
const yaml = require("js-yaml");

// Check changelog directory.
if (!process.env.CHANGELOG_DIR) {
    console.log("CHANGELOG_DIR not defined, exiting.");
    process.exit(1);
}

const ChangelogFilePath = `../../../${process.env.CHANGELOG_DIR}`;

// Regexes (kept in sync with changelog.js)
const HeaderRegex = /^\s*(?::cl:|🆑) *([a-z0-9_\-, ]+)?/im; // :cl: or 🆑 [0] followed by optional author name [1]
const EntryRegex = /^ *[*-]? *(add|remove|tweak|fix): *([^\n\r]+)\r?$/gim; // * or - followed by change type [0] and change message [1]
const PullRequestCommitRegex = /(^Merge (pull request|branch|remote)|\(#\d+\)\s*$)/i;

// Main function
async function main() {
    const eventPath = process.env.GITHUB_EVENT_PATH;
    if (!eventPath || !fs.existsSync(eventPath)) {
        console.log("GITHUB_EVENT_PATH not set or missing, exiting.");
        process.exit(1);
    }

    const event = JSON.parse(fs.readFileSync(eventPath, "utf8"));
    const commits = Array.isArray(event.commits) ? event.commits : [];

    let highestId = getHighestCLNumber();
    const newEntries = [];

    for (const commit of commits) {
        if (!commit.distinct)
            continue;

        const message = commit.message || "";
        const subject = message.split("\n", 1)[0];

        // Pull request commits are handled by the pull request changelog workflow.
        if (PullRequestCommitRegex.test(subject))
            continue;

        if (commit.author && commit.author.name === "github-actions[bot]")
            continue;

        const headerMatch = message.match(HeaderRegex);
        if (!headerMatch)
            continue;

        const changes = getChanges(message.slice(headerMatch.index + headerMatch[0].length));
        if (changes.length === 0)
            continue;

        let author = headerMatch[1];
        if (author)
            author = author.trim();
        else
            author = (commit.author && (commit.author.username || commit.author.name)) || "unknown";

        newEntries.push({
            author: author,
            changes: changes,
            id: ++highestId,
            time: formatTime(commit.timestamp),
            url: `https://github.com/${process.env.GITHUB_REPOSITORY}/commit/${commit.id}`,
        });

        console.log(`Found changelog entry in commit ${commit.id}`);
    }

    if (newEntries.length === 0) {
        console.log("No changelog entries found in pushed commits, skipping");
        return;
    }

    writeChangelog(newEntries);
    console.log(`Changelog updated with ${newEntries.length} new entr${newEntries.length === 1 ? "y" : "ies"}`);
}

// Get all changes from a changelog block
function getChanges(body) {
    const entries = [];

    for (const match of body.matchAll(EntryRegex)) {
        let type;

        switch (match[1].toLowerCase()) {
            case "add":
                type = "Add";
                break;
            case "remove":
                type = "Remove";
                break;
            case "tweak":
                type = "Tweak";
                break;
            case "fix":
                type = "Fix";
                break;
            default:
                break;
        }

        if (type) {
            entries.push({
                type: type,
                message: match[2],
            });
        }
    }

    return entries;
}

// Get the highest changelog number from the changelogs file
function getHighestCLNumber() {
    if (!fs.existsSync(ChangelogFilePath))
        return 0;

    const file = fs.readFileSync(ChangelogFilePath, "utf8");
    const data = yaml.load(file);
    const entries = data && data.Entries ? Array.from(data.Entries) : [];
    const clNumbers = entries.map((entry) => entry.id);

    return Math.max(...clNumbers, 0);
}

// Append entries to the changelog file, preserving top-level fields like Name and Order
function writeChangelog(entries) {
    const block = yaml.dump(entries, { indent: 2 }).replace(/^---\n?/, "");

    if (!fs.existsSync(ChangelogFilePath)) {
        fs.writeFileSync(ChangelogFilePath, "Entries:\n" + block);
        return;
    }

    const file = fs.readFileSync(ChangelogFilePath, "utf8").replace(/\s+$/, "\n");
    fs.writeFileSync(ChangelogFilePath, file + block);
}

// Convert a GitHub timestamp (ISO 8601) to the format the client expects
function formatTime(timestamp) {
    const date = timestamp ? new Date(timestamp) : new Date();
    if (Number.isNaN(date.getTime()))
        return new Date().toISOString().replace(/\.\d{3}Z$/, ".0000000+00:00");

    return date.toISOString().replace(/\.\d{3}Z$/, ".0000000+00:00");
}

// Run main
main();
