#!/usr/bin/env python3
"""Generate the genital organ catalog (Resources/Prototypes/_PS/Organs/genital_organs.yml)
and its type locale from the existing genital marking library.

The organ system reuses the genital markings purely as render targets (layering, color links,
clothing occlusion), so the catalog is derived from their ids instead of duplicating sprites.

Run from the repository root:  python3 Tools/gen_genital_organ_catalog.py
"""

import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKING_FILES = [
    "Resources/Prototypes/Entities/Mobs/Customization/Markings/genitals.yml",
    "Resources/Prototypes/Entities/Mobs/Customization/Markings/butts_and_bellies.yml",
    "Resources/Prototypes/_PS/Entities/Mobs/Customization/Markings/genitals.yml",
]
CATALOG_PATH = "Resources/Prototypes/_PS/Organs/genital_organs.yml"
LOCALE_PATH = "Resources/Locale/en-US/_PS/organs/organs.ftl"


def read_ids():
    ids = set()
    for rel in MARKING_FILES:
        text = open(os.path.join(REPO, rel), encoding="utf-8").read()
        ids |= set(re.findall(r"^\s*id:\s*(\S+)", text, re.M))
    return ids


def main():
    ids = read_ids()
    out = [
        "# GENERATED by Tools/gen_genital_organ_catalog.py -- do not edit by hand.",
        "# Organ types and size -> marking mapping, built from the existing genital marking library.",
        "",
    ]
    loc = []

    penises = [
        ("Human", "human"), ("Knotted", "knotted"), ("Flared", "flared"),
        ("Tapered", "tapered"), ("Barbknot", "barbknot"), ("Hemi", "hemi"),
        ("Hemiknot", "hemiknot"), ("Tipknotted", "tipknotted"),
        ("Tentacle", "tentacle"), ("Nondescript", "nondescript"),
    ]
    out.append("# region Penis")
    for tid, key in penises:
        out += ["- type: genitalOrgan", f"  id: Penis{tid}", f"  name: genital-organ-penis-{key}",
                "  genitalType: Penis", "  sizes:"]
        for size in range(1, 6):
            flaccid = f"Genital-Penis-{tid}-{size}-0"
            aroused = f"Genital-Penis-{tid}-{size}-1"
            if flaccid not in ids:
                continue
            out += [f"    - name: genital-size-{size}", f"      flaccid: {flaccid}"]
            if aroused in ids:
                out.append(f"      aroused: {aroused}")
        out.append("")
    loc.append("# Penis types")
    loc += [f"genital-organ-penis-{key} = {tid}" for tid, key in penises]
    out += ["# endregion", ""]

    out.append("# region Balls")
    for tid, key, max_size in [("Single", "single", 5), ("Sheath", "sheath", 5), ("Small", "small", 3)]:
        out += ["- type: genitalOrgan", f"  id: Balls{tid}", f"  name: genital-organ-balls-{key}",
                "  genitalType: Balls", "  sizes:"]
        for size in range(1, max_size + 1):
            flaccid = f"Genital-Balls-{tid}{size}"
            if flaccid not in ids:
                continue
            # Palmtree: balls have no aroused state, matching breasts. Where an aroused
            # (*Alt) sprite exists, use it as the standard/only sprite instead. Do not emit
            # an aroused marking for them.
            aroused = f"{flaccid}Alt"
            if aroused in ids:
                flaccid = aroused
            out += [f"    - name: genital-size-{size}", f"      flaccid: {flaccid}"]
        out.append("")
    loc += ["# Balls types", "genital-organ-balls-single = Single",
            "genital-organ-balls-sheath = Sheathed", "genital-organ-balls-small = Small"]
    out += ["# endregion", ""]

    out.append("# region Vagina")
    vaginas = [
        ("Human", "human", [("standard", ""), ("small", "Small")]),
        ("Gaping", "gaping", [("standard", ""), ("small", "Small")]),
        ("Tentacle", "tentacle", [("standard", ""), ("small", "Small")]),
        ("Dentata", "dentata", [("standard", "")]),
        ("Hairy", "hairy", [("standard", "")]),
        ("Furred", "furred", [("standard", "")]),
        ("Spade", "spade", [("standard", "")]),
    ]
    for tid, key, sizes in vaginas:
        out += ["- type: genitalOrgan", f"  id: Vagina{tid}", f"  name: genital-organ-vagina-{key}",
                "  genitalType: Vagina", "  sizes:"]
        for size_key, suffix in sizes:
            flaccid = f"GenitalVagina{tid}{suffix}"
            aroused = f"GenitalVagina{tid}{suffix}Alt"
            if flaccid not in ids:
                continue
            out += [f"    - name: genital-size-{size_key}", f"      flaccid: {flaccid}"]
            if aroused in ids:
                out.append(f"      aroused: {aroused}")
        out.append("")
    loc.append("# Vagina types")
    loc += [f"genital-organ-vagina-{key} = {tid}" for tid, key, _ in vaginas]
    out += ["# endregion", ""]

    out.append("# region Breasts")
    coyote = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o",
              "massive", "giga", "impossible"]
    out += ["- type: genitalOrgan", "  id: BreastsCoyote", "  name: genital-organ-breasts-coyote",
            "  genitalType: Breasts", "  sizes:"]
    for key in coyote:
        mid = f"GenitalBreastsRound{key.capitalize()}"
        if mid not in ids:
            continue
        out += [f"    - name: genital-size-{key}", f"      flaccid: {mid}"]
        skintoned = f"GenitalBreastsRoundSkintoned{key.capitalize()}"
        if skintoned in ids:
            out.append(f"      skintoned: {skintoned}")
    out.append("")
    out += ["- type: genitalOrgan", "  id: BreastsSplurt", "  name: genital-organ-breasts-splurt",
            "  genitalType: Breasts", "  sizes:"]
    for size in range(0, 18):
        mid = f"PSGenitalBreasts{size}"
        if mid not in ids:
            continue
        out += [f"    - name: genital-size-{size}", f"      flaccid: {mid}"]
        skintoned = f"PSGenitalBreastsSkintoned{size}"
        if skintoned in ids:
            out.append(f"      skintoned: {skintoned}")
    out.append("")
    loc += ["# Breasts types", "genital-organ-breasts-coyote = Coyote (round pair)",
            "genital-organ-breasts-splurt = Splurt (round pair)"]
    out += ["# endregion", ""]

    out.append("# region Butt")
    for suffix, key in [("", "standard"), ("Skintoned", "skintoned")]:
        out += ["- type: genitalOrgan", f"  id: Butt{key.capitalize()}", f"  name: genital-organ-butt-{key}",
                "  genitalType: Butt", "  sizes:"]
        for size in range(1, 5):
            mid = f"GenitalButt{suffix}{size}"
            if mid not in ids:
                continue
            out += [f"    - name: genital-size-{size}", f"      flaccid: {mid}"]
        out.append("")
    loc += ["# Butt types", "genital-organ-butt-standard = Standard", "genital-organ-butt-skintoned = Skintoned"]
    out += ["# endregion", ""]

    out.append("# region Belly")
    for prefix, key, max_size in [("Tummy", "tummy", 5), ("Obese", "obese", 5)]:
        out += ["- type: genitalOrgan", f"  id: Belly{prefix}", f"  name: genital-organ-belly-{key}",
                "  genitalType: Belly", "  sizes:"]
        for size in range(1, max_size + 1):
            mid = f"GenitalBelly{prefix}{size}"
            if mid not in ids:
                continue
            out += [f"    - name: genital-size-{size}", f"      flaccid: {mid}"]
        out.append("")
    out += ["- type: genitalOrgan", "  id: BellyUdders", "  name: genital-organ-belly-udders",
            "  genitalType: Belly", "  sizes:"]
    if "GenitalBellyUdders1" in ids:
        out += ["    - name: genital-size-1", "      flaccid: GenitalBellyUdders1"]
    out.append("")
    loc += ["# Belly types", "genital-organ-belly-tummy = Tummy", "genital-organ-belly-obese = Round",
            "genital-organ-belly-udders = Udders"]
    out += ["# endregion"]

    os.makedirs(os.path.dirname(os.path.join(REPO, CATALOG_PATH)), exist_ok=True)
    os.makedirs(os.path.dirname(os.path.join(REPO, LOCALE_PATH)), exist_ok=True)
    open(os.path.join(REPO, CATALOG_PATH), "w", encoding="utf-8").write("\n".join(out) + "\n")
    open(os.path.join(REPO, LOCALE_PATH), "w", encoding="utf-8").write("\n".join(loc) + "\n")
    print(f"Wrote {CATALOG_PATH} and {LOCALE_PATH}")


if __name__ == "__main__":
    main()
